### ISSUE TITLE
CC Crash

### ISSUE THREAD

**Issue by Venom983** [voidpublic/MCZombie#43]
So basically if you've used /ref and then hide later on, when you unhide(/hide again) you will crash.

**Comment by voidpublic** [comment]
Will have to test

**Comment by voidpublic** [comment]
might get to this today

**Comment by voidpublic** [comment]
"today"

**Comment by voidpublic** [comment]
Fixed with 5e85b9e32f08780a6f125747b16d2d0edce4d6a1
