### ISSUE TITLE
Whoip automatic redirected error

### ISSUE THREAD

**Issue by Venom983** [voidpublic/MCZombie#45]
Type: WebException
Source: System
Message: Too many automatic redirections were attempted.
Target: GetResponse
Trace:    at System.Net.HttpWebRequest.GetResponse()
   at MCForge.Player.GetIPLocation(String IP)
   at MCForge.Commands.CmdWhoip.Use(Player p, String message)
   at MCForge.Player.<>c__DisplayClass1f.<HandleCommand>b__1b()

--------------------------------------------------------------------------------------------------
I assume this is an issue with the IP tracker owners modifying their html.

**Comment by Venom983** [comment]
This error is for both Whoip and Location.

**Comment by voidpublic** [comment]
scheduled this and many other things for today.

**Comment by voidpublic** [comment]
Ok so the reason that its not working anymore is that the IP tracker is not allowing requests from automated system anymore:

	<div class='lookupredempty' align="center">
	<p style="margin-top:10px;">You have entered this page because you've used illegal characters in your http request and that is not allowed on this domain.
Another possibility is that your browser send to server empty User Agent Strings. Please
show to us User Agent Strings and you will be able to see our site.
</p>
<br />
<p>
<a href="javascript:goback()">Go Back To The Previosly Page</a>
</p>

**Comment by voidpublic** [comment]
d7cce5ab1317246cc31e5c44dda5649414f8dacf

disabled for now, there is no site that allows lookups + endless lookups from an automatic script
